name: ci

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: lint
        run: make lint

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: build
        run: make build
      - name: bin
        uses: actions/upload-artifact@v2
        with:
          name: mikrotik-exporter
          path: ./bin/mikrotik-exporter

  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: tests
        run: make cover
      - name: cover
        uses: actions/upload-artifact@v2
        with:
          name: cover
          path: ./cover.html